# Generated by Django 4.2.7 on 2023-12-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_imagen_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/post_default.png', null=True, upload_to='posts/img'),
        ),
    ]
